### ISSUE TITLE
PHP 8.0 Warning when cv is used to run CiviCRM scheduled jobs via cron. 

### ISSUE THREAD

**Issue by paulrooney** [backdrop-contrib/antiscan#2]
Example:
/path/to/php/8.0/bin/php -d memory_limit=256M /path/to/cv api job.execute --user=civicron --cwd=/path/to/httpdocs --quiet

Output to watchdog:
Undefined array key "REQUEST_URI" in antiscan_boot() (line 56 of antiscan/antiscan.module).

**Comment by findlabnet** [comment]
Thanks @paulrooney, I'll get back to this in a few days.

**Comment by findlabnet** [comment]
In order to possibly use a PHP version lower than 7, I fixed this issue using the older syntax.
A new version of the module (1.0.7) is available.
Thanks again @paulrooney for your valuable contribution and Happy New Year!
