### ISSUE TITLE
Warning: Cannot modify header information - headers already sent

### ISSUE THREAD

**Issue by izmeez** [backdrop-contrib/antiscan#5]
New to the antiscan module and not sure how to interpret this event. Also running antibot and honeypot modules on the same site. An anonymous visitor to the contact page resulted in the following watchdog entry:

```Type = php; Message = Warning: Cannot modify header information - headers already sent by (output started at /core/includes/bootstrap.inc:3133) in antiscan_action() (line 164 of /modules/antiscan/antiscan.module).```

Subsequent visits to other legitimate paths were blocked as a result.

The ip address is not in the AbuseIPDB. But, it is a Chinese ip address.

**Comment by findlabnet** [comment]
This problem is explained here:
https://github.com/backdrop-contrib/ip_blocking?tab=readme-ov-file#known-issues

I will also add this explanation to the README.md for this module.
